### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by Flohack74** [ubports/telegram-app#1]
Latest version is missing some translations. Update POT file and hand it out to some translators.

**Comment by NeoTheThird** [comment]
Can we continue to use launchpad for this somehow?

**Comment by Flohack74** [comment]
No idea tbh how to hook up Github to it....

**Comment by NeoTheThird** [comment]
It is possible. We will do it for the rest of the project as well. Let's wait for now and look into it.

**Comment by Flohack74** [comment]
Closing this here, as further translations will be done at https://translate.ubports.com :)
