### ISSUE TITLE
Forwarding messages in V2.5.0

### ISSUE THREAD

**Issue by j2g2rp** [ubports/telegram-app#104]
Hi.
Looks like forwarding messages can be a mess, at least in last version (not sure if this happens in previous).

Problem:
select a message from chat 1 to forward.
select chat to forward (same chat1)
A message from another chatX is fordwared.

Espectation:
Select a message from hat 1.
forward message to chat1
The message you choosed is forwared.

Thanks for new version :)

**Comment by Flohack74** [comment]
Its already fixed in next beta build (live in 10mins) :)
