### ISSUE TITLE
No notifications thumbnails.

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/telegram-app#106]
Supergroups displays no thumbnails onde notificativo.

**Comment by Flohack74** [comment]
Can you please re-test with this version? https://github.com/ubports/telegram-app/releases/download/v2.5.3beta/com.ubuntu.telegram_2.5.2.0_armhf.click

**Comment by GI9VANNI** [comment]
@Flohack74 What do you mean by "thumbnails"?

**Comment by Flohack74** [comment]
I dont know, the original poster used this word ;)

**Comment by Flohack74** [comment]
@rubencarneiro Are you still seeing this with the latest version?

**Comment by rubencarneiro** [comment]
No. Thumbnails are showing.Working ok
