### ISSUE TITLE
Gap between loaded messages V2.5.0

### ISSUE THREAD

**Issue by j2g2rp** [ubports/telegram-app#108]
Looks like sometimes telegrm can't load all messages lefting a gap between  the loaded messages and previous sesion loaded messages.
Even closing app and openning it the app can't load the gap of messages.

**Comment by Flohack74** [comment]
Can you make me a screenshot plz?

**Comment by j2g2rp** [comment]
![screenshot20171105_161955301](https://user-images.githubusercontent.com/28528967/32430199-867118a2-c2ce-11e7-949f-924aba6e426c.png)
![screenshot20171106_013032941](https://user-images.githubusercontent.com/28528967/32430200-869c4eb4-c2ce-11e7-8042-fd26aeaa0826.png)
Sure. I didn't know how to do it.
I took two screenshots, in diferent times. The gap persist

**Comment by Flohack74** [comment]
Interesting thing.... Did not see this so far...

**Comment by j2g2rp** [comment]
there is something that i could do to track it?

**Comment by mauricioduarte01** [comment]
Hello guys, this happened to me a few times, I had to wait for a few minutes or reopen the app to get the messages loaded. I don't know if this has something to do with bad 4G reception (intermittent). Anyways, great job Flo and devs! I am just missing the stickers :D

**Comment by Flohack74** [comment]
There are a lot of problems. Telegram never handled disconnect/reconnect correctly. It simply sometimes looses the state and you dont get any update, cannot write messages or mark them as read etc. The connection indicator shows that you are connected, but in fact you aren´t. But this is nothing that is specific to supergroups. I want to know here, does message ommittance only appear in supergroups, or also in normal ones?

**Comment by mauricioduarte01** [comment]
@Flohack74 Florian, this happens to me with normal chat too. Actually now when trying with stickers update, I was having the same issue, stickers were not showing for me in realtime until I had to reopen the app and then it reloaded everything, messages and stickers. But the missing messages thingy is kind of random. Thanks

**Comment by j2g2rp** [comment]
What i can see from now is that.
I decided to don't open telegram app during yesterday evening, so I had about 400 messages left unread from Ubuports supergroup. I readed those messages through telegram desktop oficial app.

Then, this morning i tried to load those messages ( i think that they aren't indexed).
Since telegram always put you in last message i began to load messages.
In my case it doesn't looks like a conection problem. The gaps are generated during the load of messages don't indexed. I mean, while you are going to reading previous messages there is a point where telegram have to access to not indexed messages. In that moment a gap is generated.

I can't see any errors in telegram log...

I can't see if this happens in normal chats since i haven't this amount of messages in any chat hehe.

do you need any aditional info?

**Comment by Flohack74** [comment]
Found the problem, I will commit a fix shortly, plz test from Github Beta in about 1hr or so ^
