### ISSUE TITLE
supergroups do not open

### ISSUE THREAD

**Issue by sambuccid** [ubports/telegram-app#112]
I don't know if this issue is already knowed.

When i try to open a supergroup or a channel, it does not open and every supergroups and channels appear selected.
Previously the supergroups and channels were working.

![not selected](https://user-images.githubusercontent.com/26792034/32771474-14c0078a-c923-11e7-8ab8-c9d52c1fbf01.png)

![selected](https://user-images.githubusercontent.com/26792034/32771491-1c17c3d8-c923-11e7-8abd-b8c311ab525f.png)

if I close the app and reopen it, it work again.
Is the first time that this issue appear, and this isn't important.

**Comment by Flohack74** [comment]
Can you check again please with the latest build which is linked here in Github?

**Comment by sambuccid** [comment]
I have pre-release 2.5.0

**Comment by PeterNerlich** [comment]
Please update to the current version `2.5.2.0` and report whether this still occurs for you.

**Comment by Flohack74** [comment]
This is resolved by the latest version 2.5.2 actually ;)

**Comment by sambuccid** [comment]
thanks

**Comment by sambuccid** [comment]
The same problem seems to reappear

**Comment by sambuccid** [comment]
I realized that the problem happens because I disable push notifications
