### ISSUE TITLE
Russian translation is bogus

### ISSUE THREAD

**Issue by kwah-gh** [ubports/telegram-app#118]
In places, where the date / time stamp should be mentioned the following is observed: `ДДД ЧЧ:мм` or `дд МММ`. Looks like a pretty basic mistake, where date/time format strings (`DDD HH:mm` and `dd MMM`) were translated.

**Comment by Flohack74** [comment]
Please visit https://translate.ubports.com and start fixing it for us ;)

**Comment by kwah-gh** [comment]
Will do. I've seen in other projects that they specially leave "notes to translators" by commenting the strings that denote date/time and other formats that should be left in the translated text "as is". So, if this is not done for strings in telegram app, might be wise to do so ;)

**Comment by Flohack74** [comment]
You know this App went a long way... It was a fork from Sigram, called Cutegram that Canonical forked again and tried to get it right. But somewhere they failed. And now its a big mess, and we are a small team. Such annotations exists on some place, on others not. Feel free to put them there, but please send only PRs for the pot file, po's are autogenerated...

**Comment by kwah-gh** [comment]
Translation fixed.

**Comment by Flohack74** [comment]
Cool! Translations get merged every Sunday. With the next stable release (ETA 1 week) you should see them appearing ;)
