### ISSUE TITLE
No push notifications for channel messages

### ISSUE THREAD

**Issue by GI9VANNI** [ubports/telegram-app#127]
Hello!
Using your app on a Nexus 5 with Ubuntu Touch, I noticed that stickers notifications do not appear.
I'm not talking about the smilies integrated into the keyboard, but about the Telegram stickers.
Can you solve this problem?

**Comment by criztovyl** [comment]
Could you look out for "unknown type" (or something similar) in your push-client log? (`/home/phablet/.cache/upstart/ubuntu-push-client.log`) I think I saw such errors there but I am not sure.

**Comment by GI9VANNI** [comment]
I found 7 files named ubuntu-push-client.log.**x**.gz with **x** from 1 to 7. Do I have to attach them?

**Comment by Flohack74** [comment]
Please attach only the latest file. 1 should be enough

**Comment by GI9VANNI** [comment]
[ubuntu-push-client.log.7.gz](https://github.com/ubports/telegram-app/files/1589240/ubuntu-push-client.log.7.gz)

**Comment by criztovyl** [comment]
Try `.1`, it's more recent then `.7` :)

**Comment by GI9VANNI** [comment]
[ubuntu-push-client.log.1.gz](https://github.com/ubports/telegram-app/files/1589936/ubuntu-push-client.log.1.gz)

**Comment by Flohack74** [comment]
Erm wait a second guys, are we talking about pop-up of notifications outside telegram, or messages inside telegram groups where stickers dont show up?

**Comment by Flohack74** [comment]
Ok I think I saw something, when we introduced channel/supergroup support, we might have forgot something to patch in the helper :)

**Comment by Flohack74** [comment]
Push helper does not know about:
`payload:{"message":{"loc_key":"CHANNEL_MESSAGE_TEXT","loc_args":["...","..."],"custom":{"msg_id":"495","channel_id":"1003872209"}},"notification":{"tag":"chat","card":{"summary":"...","body":"...","popup":true,"persist":true},"sound":"buzz.mp3","vibrate":{"pattern":[200,100],"duration":200,"repeat":2},"emblem-counter":{"count":57,"visible":true}}}`
This is true for channels only, supergroups are fine.

**Comment by Flohack74** [comment]
@GI9VANNI I can send you a test version to try if it works for you now.

**Comment by GI9VANNI** [comment]
The test version works!
