### ISSUE TITLE
Telegram hangs sending registration code in xenial both M10 and N5

### ISSUE THREAD

**Issue by gabriel-lucas** [ubports/telegram-app#133]
**What happened:** I open Telegram 2.5.2.0 for the first time, select country and phone number but it hangs when sending the registration code. It does not send the sms/code back and the app does not ask for it.

**What I expected to happen:** Receive the confimation code correctly and get to the next screen asking for it.

**Steps to reproduce:** 
- Mobile connected via wifi to Internet, no mobile data available.
- Open telegram for the first time.
- Select country
- Introduce the phone number
- Confirm the phone number

**Logs**
$ cat .cache/upstart/application-click-com.ubuntu.telegram_telegram_2.5.2.0.log
https://paste.ubuntu.com/26399142/

**Versions**:
SO: Ubuntu 16.04 (r205)
Telegram: 2.5.2.0

Might be related:
https://github.com/ubports/telegram-app/issues/99

**Comment by zubozrout** [comment]
Well, this also happens with Meizu MX4 arale - so I can confirm this.

**Comment by Flohack74** [comment]
Telegram is not yet compiled for 16.04 so it must break :)

BR

**Comment by Flohack74** [comment]
There is a branch now to try to get everything built by clickable, see here: https://github.com/ubports/telegram-app/tree/bleeding-clickable - any help is appreciated.

**Comment by ChrisHad** [comment]
Hi
I seem to be getting the same issue on Oneplus One with 16.04.
[log](http://paste.ubuntu.com/p/pQXwSwzvvy/)

Has development moved to a different branch?

Regards,
Chris

**Comment by Flohack74** [comment]
No. There is currently a problem that you cannot register new accounts in Telegram, thats the only one I am aware of. Usual xenial branch works well if the phone is already registered...

**Comment by Flohack74** [comment]
This means you will receive the SMS code, but then after entering the code you get PHONE_NUMBER_UNOCCUPIED which is not the issue we were talking about here.
