### ISSUE TITLE
Control of notifications with multiple devices

### ISSUE THREAD

**Issue by GI9VANNI** [ubports/telegram-app#135]
Hello!
When you receive a message and you have 2 or more devices connected to the same Telegram account, the notification reaches everyone.
The point is that if you open the message on one of these devices, the notification disappears on other devices or at least the notification LED goes out. With Ubuntu Touch no.

For example, if I have an Android smartphone and one with Ubuntu Touch:
1) I receive a message, I open it with the Ubuntu Phone, and at that moment the notification LED of the Android smartphone goes out.
2) I receive a message, I open it with the Android smartphone, and the notification LED of the Ubuntu Phone stays on.

Can you do something on Ubuntu Touch to bring it as the first example?

**Comment by Flohack74** [comment]
Hi Giovanni,

not at the moment, as this requires telegram to send us "read" notifications, which obviously was not put into the current push API. But I will try to get their opinion...

**Comment by GI9VANNI** [comment]
We hope well...

**Comment by Flohack74** [comment]
They will put the code into the test system today or so, I will keep an eye on that. Basically it seams easy to implement ;)

**Comment by Flohack74** [comment]
This was just now implemented on the Telegram side!

**Comment by Cecon83** [comment]
Hello,

What happen with this issue , we have found some solution.

Thanks

**Comment by Flohack74** [comment]
Yes it should work, was implemented on Telegram side by sending an empty push message to remove the notification on UT.

**Comment by Cecon83** [comment]
Is it possible that there is still a notification even if one of the two device open the message?

**Comment by Flohack74** [comment]
I tested this again but I can only test with Desktop and UT. Any message I read on the Desktop is deleted form the device as it should be.

**Comment by GI9VANNI** [comment]
Later I will test with various devices, but I'm sure it works well.

**Comment by Cecon83** [comment]
Exactly i dont want disappears notification  if i open the message on one of two devices.

**Comment by Flohack74** [comment]
Ok NOW I understand. Well thats a matter of preference I would say, but we cannot change the way Telegram works. So its either on or off for all users. And I think the majority wants that the messages disappear.

**Comment by GI9VANNI** [comment]
@Flohack74 Great job! I have tested three devices and it works well. I understand that someone can not like it, but that's how Telegram works on Desktop, Android and other systems and it's better to have a uniform experience. So I can confirm that this issue has been solved.
