### ISSUE TITLE
TelegramQML needs to expose channel permissions

### ISSUE THREAD

**Issue by mymike00** [ubports/telegram-app#141]
TelegramQML should let you know if you are the owner/can send a message/only read/etc... to a channel

**Comment by b0tus** [comment]
Im not subscribed anymore!!!!!

Sendt fra min iPhone

5. mar. 2018 kl. 21:15 skrev Florian Leeber <notifications@github.com<mailto:notifications@github.com>>:


Closed #141<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fubports%2Ftelegram-app%2Fissues%2F141&data=02%7C01%7C%7Ccc8893eb2adb4f61dd4308d582d5cbe5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636558777116733518&sdata=ZJAkXyYfrFr%2FQy5rnCMBHc5v72zYwbhvU4shjm0RSmQ%3D&reserved=0>.

**Comment by Flohack74** [comment]
What can I do against this, this is Github, not my personal tracker...
