### ISSUE TITLE
Regression in v2.5.3.0 : Telegram displays no or just one of the messages

### ISSUE THREAD

**Issue by Pete413** [ubports/telegram-app#151]
Yesterday, I updated to Telegram v2.5.3.0 and there is a severe regression from previous versions: 

After updating: When I open Telegram and tap on a contact, only the last message or no message at all (depending on the contact) is there. All other messages are gone!

I did some experiments by restarting the app and restarting the smartphone. Strangely enough, only once I could see all messages, except for one of the contacts, in which there still was no message visible. However, restarting the app once more lead to the miserable state of displaying one or no message. Now I still see one or no message. 

Thanks for your help!

System: OPO with UBPorts 15.04

**Comment by Flohack74** [comment]
Can you please updatre again, I made 2 minor releases today.

**Comment by Pete413** [comment]
Oh, there is now also another problem.
I updated to v2.5.3.1 and the problem persisted. Now, I updated to v2.5.3.2 and the problem also persisted. However, now Telegram crashed and upon restart it seems to have forgotten his profile entirely. It starts with the Welcome start screen (as it was before I had created a Telegram account).
What do you suggest?

**Comment by Flohack74** [comment]
Please close the APp, remove .config/com.ubuntu.telegram folder completly and try to re-login. No data will be lost

**Comment by Pete413** [comment]
Thanks a lot! It worked. After deleting .config/com.ubuntu.telegram, I logged in again and
(1) the profile is here again
(2) the issue described in this bug is solved. I see all messages again. 

Btw: the funny thing is that I can see now the photo-message which a friend had sent some weeks ago, but which never got through. Now, also this photo is here.  :-)

Shall I close this bug? Or shall I leave it open, if anyone faces the same problems after updating to v2.5.3.0/1/2?

**Comment by Flohack74** [comment]
I can close it for you ;)
