### ISSUE TITLE
No log out facility 

### ISSUE THREAD

**Issue by UKPhil** [ubports/telegram-app#154]
The log out facility is missing from the Telegram app.

This is present in the web app and android, but not in the Ubuntu Touch app.

**Comment by Flohack74** [comment]
It is not obvious since the App was written to support multiple accounts at the same time but please do:
- Open the hamburger menu
- Go to settings
- On the bottom you can sign out from the account on *this* device

You can not close other sessions. Is your ticket about this feature?

**Comment by UKPhil** [comment]
It sure is, sorry I did not see that. I will close it down. Thanks.
