### ISSUE TITLE
Add night mode facility

### ISSUE THREAD

**Issue by UKPhil** [ubports/telegram-app#155]
One of the Windows Telegram app that is missing from the Ubuntu Touch app is Night Mode. This is very useful and would be fantastic in Touch.

**Comment by Flohack74** [comment]
Now that you name it: We are *right now* working on it ;)

**Comment by UKPhil** [comment]
That is great news thanks. I look  forward to seeing it.

**Comment by Flohack74** [comment]
PM me on Telegram for a test build.

**Comment by UKPhil** [comment]
Sure, but I need your number as I have not got your details

**Comment by Flohack74** [comment]
Night mode will be in the next release, we finished the feature now.

**Comment by UKPhil** [comment]
@Flohack74  that is great news, look forward to downloading and using. Thanks for all your efforts.
