### ISSUE TITLE
Hang Inverification process

### ISSUE THREAD

**Issue by selfieebritto** [ubports/telegram-app#158]
![screenshot20180318_175228887](https://user-images.githubusercontent.com/11912587/37565828-924a211c-2ad6-11e8-802c-99bf79d68c8b.png)

**Comment by Flohack74** [comment]
Need more info dude. 16.04, 15.04 waht device channel etc...

**Comment by selfieebritto** [comment]
__build version : Ubuntu Touch 16.04 LTS (Xenial Xerus)__
__device : titan (moto g 2014)__
i know this UT build is still in development. Now i moved to vivid yesterday.
thanks for quick response dude. have a good day

**Comment by Flohack74** [comment]
16.04 telegram is not working right now, as can be seen in other places :)
