### ISSUE TITLE
code formatted text not handled

### ISSUE THREAD

**Issue by mymike00** [ubports/telegram-app#160]
the code formatted text (the one styled using ` `` `) should be handled using a mono font

![immagine](https://user-images.githubusercontent.com/28359593/37903587-c1729e38-30f8-11e8-8d7f-3dbab62b7b4c.png)
example on telegram desktop how it is viewed

**Comment by Flohack74** [comment]
This is a bit more complicated. In addition to the inline text Telegram uses special extra fields for markup, to distinguish a normal backtick from formatted text. Not all text is to be converted, it seems. See https://core.telegram.org/bots/api#messageentity
