### ISSUE TITLE
"Banned" for no reason

### ISSUE THREAD

**Issue by Mr-ex777** [ubports/telegram-app#161]
Starting from 13:00 PM today i had been unable to message in  telegram at all in all but one of the channels i am in because i was "Banned/Limited" due to "Spam", although it does not seem like anyone reported me or anything. I can join channels, read their contents, just not send messages because i was "Banned". 

It was clearly not any local admins who did it, i've told them to unban me but i can't talk even if i am unbanned, and i can talk at one of the channels where i am in. (However, any messaging outside that channel auto fails.) I don't know if somebody mistakenly clicked the report button on me but i did not attempt any pms, and i only talk at groups. Also if i were reported from spam i should not be able to talk in the one group in the first place.

Also i just found out i seem to get banned when i chat in both app and browser version. If i chatted in app version then browser version beforehand, i got limited.

Very frustrating, already contacted numerous staff outlets such as twitter, mail, spam info bot and reddit to no avail, all fall on deaf ears. Can somebody please help me?

**Comment by Flohack74** [comment]
What device and OS you are using?

**Comment by Mr-ex777** [comment]
Android, samsung c7. Also chats in desktop but if i do so in both devices i get limited.

**Comment by Flohack74** [comment]
Please do contact Telegram support. you found the wrong place, this is Telegram for Ubuntu Touch ;)
