### ISSUE TITLE
Link thumbnail is displayed giant

### ISSUE THREAD

**Issue by mateosalta** [ubports/telegram-app#162]
When linking a page, the thumbnail seems rather large and commands more attention then in should. 
![img_20180407_185945_728](https://user-images.githubusercontent.com/1965279/38461452-fe5c0130-3a95-11e8-9e56-a1fa34b194b1.jpg)
![screenshot_20180407-185018](https://user-images.githubusercontent.com/1965279/38461454-093850b8-3a96-11e8-87cf-a1850f303981.png)
As a user is primarily concerned with the link, I propose a downsize of the area used for link preview images.

**Comment by Flohack74** [comment]
I think this is fixed now :)
