### ISSUE TITLE
Wrong message when «User1adds Usser2 to a group»

### ISSUE THREAD

**Issue by cibersheep** [ubports/telegram-app#167]
- In a group, ask to user1 to add user2
- Expected result: for all user to see message «user1 added user2 to the group» (check desktop screenshot)
![imatge](https://user-images.githubusercontent.com/6640041/39470414-e10579e4-4d3d-11e8-8ca5-5e03e3c6f4b7.png)

- What happends in UT Telegram: user receive message «user1 joined the group» (check UT Telegram screenshot)
![imatge](https://user-images.githubusercontent.com/6640041/39470478-4acd0630-4d3e-11e8-951a-5eb4172c8ac3.png)

**Comment by cibersheep** [comment]
Oh, I see. I just reported because I thought I had a bad translation.
It is really a «cosmetic» thing. So, no pressure :) we love you anyway

**Comment by Flohack74** [comment]
I think I did it! Can you please test this for me? click is in QA group
