### ISSUE TITLE
Telegram fails to start

### ISSUE THREAD

**Issue by AlanGriffiths** [ubports/telegram-app#169]
This started happening today, and only affects one phone (my "daily driver" :), the other (and desktop) works fine. I didn't install any updates or change anything.

Clicking on "Telegram" shows the app logo full screen and then returns to the previous screen. Similarly when a notification comes in.

Power off & on and uninstalling & reinstalling have no effect.

I assume some logfiles would be useful for diagnosis, but I need an idiot's guide to finding the right ones.

**Comment by AlanGriffiths** [comment]
Deleting the cache & config didn't work. :(

Tried reinstalling again, but still the same failure. Logviewer doesn't list any telegram logs.

**Comment by NeoTheThird** [comment]
That is very odd. Time to call in @Flohack74.

**Comment by Flohack74** [comment]
Did you accidently upgrade to 16.04?

**Comment by AlanGriffiths** [comment]
No, 15.04 (r3).

**Comment by AlanGriffiths** [comment]
Fixed:
1. Uninstall telegram
2. find -name *telegram* | xargs rm -rf
3. Install telegram
4. Start telegram & sign in
