### ISSUE TITLE
[xenial] Notifications don't work

### ISSUE THREAD

**Issue by zubozrout** [ubports/telegram-app#174]
Hello,
I've just tried building latest Telegram (2.5.3) - the master branch - with clickable and it worked like a charm. It is great I can finally use it on Xenial :+1: 

However, I've noticed that I don't receive any notifications and if I agree on using Ubuntu One account nothing happens and still see the switch turned off the next time I enter the settings screen.

I've tried removing my Ubuntu One account from system accounts but even without it no prompt to enter credentials was shown.

Just adding this here as I haven't seen it reported anywhere yet though this may not be a Telegram issue but perhaps something related to Ubuntu 16.04 still not handling accounts well?

**Comment by Flohack74** [comment]
Hmm need to see this... will be not easy to understand whats going on here...

**Comment by Flohack74** [comment]
Is Telegram listed in system-settings where you can configure the notifications sound and popups?

**Comment by zubozrout** [comment]
@Flohack74 Unfortunately not. The only app that is listed in accounts is a Contact app (for Google). For example Calendar app seems to suffer from same issue - as referenced above ^)

**Comment by Flohack74** [comment]
Hmm then smth went wrong with the installation or idk. Telegram push function is registered in the app manifest normally.

**Comment by zubozrout** [comment]
Well this is apparently happening to at least one other Xenial user as well - that is having only Contacts app listed in the Accounts settings.
Cite from UBports QA and testing: "Only contacts app is listed under system settings -> security&privacy -> app permissions -> online accounts"

So I wonder what may have gone wrong. Are there some system changes that may have broke it? But why would Contacts show up normally then?

**Comment by Flohack74** [comment]
I am closing this here, on Telegram side nothing changed and this is probably related to https://github.com/ubports/ubuntu-touch/issues/602
