### ISSUE TITLE
Number banned

### ISSUE THREAD

**Issue by Zaidalkhalili** [ubports/telegram-app#213]
Hello,

I work for a cryptocurrency project as a community admin and it is my only source of income at the moment. Last night I wanted to check the channel to do my regular job but I found out that my number has been banned for no reason. Myself and another fellow admin also got banned at the same time. I was thinking maybe your bot thought we are bots for spamming scam links? For your information we have a bot in our channels that automatically deletes all spam links that get posted in our channel so this might be the reason? We added a new blacklist spam yesterday and we tested to see if our bot would delete it by pasting it in our chat, that might be the reason? 
Any help is appreciated

Thank you

**Comment by UniversalSuperBox** [comment]
Please contact [Telegram support](https://telegram.org/support) for issues relating to the Telegram service.
