### ISSUE TITLE
White screen after server side logout

### ISSUE THREAD

**Issue by dfiloni** [ubports/telegram-app#33]
When telegram-app is disconnected from the server, the app cannot start anymore, it shows a white screen instead of the login code request page (phone number is already known to app so this step is skipped).

How to reproduce:

- Login to another telegram instance
- Disconnect the affected telegram-app session from settings
- Open telegram-app on affected device
- Follow the welcome screen
- Enter phone number
- DO NOT enter code, but close telegram
- Wait 2 mins
- open telegram app again

The server will send the previous auth code again. So it looks like the server just thinks, ok code got lost, lets send it again. But the client does not change to the code input screen properly.

Log from affected user:
> Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
> [20170504 18:06:02.876 BST "UpgradeV2" nothing to do for v1
> [20170504 18:06:02.940 BST QQmlComponent: Component is not ready
> [20170504 18:06:02.940 BST "file:///opt/click.ubuntu.com/com.ubuntu.telegram/2.4.39.6/themes/Abrisham.qml:-1 File not found
> "
> [20170504 18:06:03.081 BST virtual void OnlineAccountsClient::Plugin::registerTypes(const char*) Ubuntu.OnlineAccounts.Client
> [20170504 18:06:04.662 BST QFSFileEngine::open: No file name specified
> [20170504 18:06:05.399 BST could not open containers config file  "/home/phablet/.local/share/libertine/ContainersConfig.json"
> [20170504 18:06:05.640 BST qrc:/qml/telegram.qml:204:21: Unable to assign [undefined] to QObject*
> library "/vendor/lib/egl/libGLESv2S3D_adreno.so" not found
> [20170504 18:06:06.192 BST qrc:/qml/telegram.qml:73: TypeError: Cannot read property 'registered' of null
> [20170504 18:06:06.300 BST qml: authNeeded true
> [20170504 18:06:06.300 BST qml: authLoggedIn false
> [20170504 18:06:06.350 BST qml: authPhoneChecked true
> [20170504 18:06:06.416 BST qml: authNeeded true
> [20170504 18:06:06.417 BST qml: authLoggedIn false
> [20170504 18:06:06.417 BST qml: authCodeRequested
> [20170504 18:06:13.479 BST qrc:/qml/telegram.qml:73: TypeError: Cannot read property 'registered' of null
> [20170504 18:06:53.665 BST qrc:/qml/telegram.qml:73: TypeError: Cannot read property 'registered' of null
> [20170504 18:06:56.092 BST qrc:/qml/telegram.qml:73: TypeError: Cannot read property 'registered' of null
>

**Comment by 3arn0wl** [comment]
I'm experiencing the same issue, running the latest version of the app on UBPorts Hammerhead.
I've entered my number. Now when I open the app, I get the icon and the revolving blue Kisby ring, followed by a blank white screen. Then I get a code from Telegram - but obviously there's nowhere to enter it.

**Comment by Flohack74** [comment]
@dfiloni Can you test latest release? I think we fixed it ;)

**Comment by balcy** [comment]
I'm using 2.4.42, but after being on unreliable networks in the train today, the app can no longer be started ( similar log file as reported above) and only shows a white screen.
Before I was using it for some weeks (not happened directly after registration for me)

**Comment by Flohack74** [comment]
@balcy This is another story, we are talking specifically about a problem after logging out from telegram via menu, logging in again, or quitting the App before entering the code. Network issues are a known wekaness that can confuse the app. But can you check the logfile for "authCodeRequested" message?

**Comment by balcy** [comment]
oh ok I see, I was assuming the bug was for the white screen problem in general...
Unfortunately in LogViewer the telegram log no longer dates back to the point where I had the white screen. (it is filled with recreation of the downloads folder in .cache which I had renamed). I will try next time if it happens.

**Comment by balcy** [comment]
right now I cannot find it:
````
phablet@bq:~/.cache/upstart$ cat application-click-com.ubuntu.telegram_telegram_2.4.42.0.log | grep auth
[20170913 18:35:35.395 CEST qml: authNeeded false
[20170913 18:35:35.396 CEST qml: authLoggedIn true
[20170913 18:35:35.838 CEST qml: authPhoneChecked true
[20170913 22:32:19.871 CEST qml: authNeeded false
[20170913 22:32:19.872 CEST qml: authLoggedIn true
[20170913 22:32:20.314 CEST qml: authPhoneChecked true
[20170913 23:28:39.913 CEST qml: authNeeded false
[20170913 23:28:39.914 CEST qml: authLoggedIn true
[20170913 23:28:40.232 CEST qml: authPhoneChecked true
