### ISSUE TITLE
Not possible give permission to app to use microphone

### ISSUE THREAD

**Issue by corvusd** [ubports/telegram-app#41]
When, in first time, put in microphone icon to start record a clip. The app inform you that is necessary give permission. When you put the button, open permission settings area. But the microphone permission not enabled. Not possible enable the permission. Telegram can not use the microphone.
Telegram version: 2.4.40.0
Device: Bq m10 FHD - Ubuports 27/5/17

**Comment by corvusd** [comment]
Fixed in last update ubport image.

**Comment by Flohack74** [comment]
Really? Nothing changed IMHO xD
