### ISSUE TITLE
Cannot delete history / leave chats with people who have deleted their account

### ISSUE THREAD

**Issue by bqphone** [ubports/telegram-app#42]
Hi there,

I am using bq phone E4.5
OS ubuntu 15.04 (r6) (just flashed my phone to ubports latest version).
Telegram for ubuntu v2.4.40(0)

I am failing to delete or leave chats with people who deleted (uninstalled) their telegram account. It works fine with people that are currently using telegram.

**Comment by Flohack74** [comment]
Confirmed!

**Comment by dfiloni** [comment]
Could you please test issue-42 branch? The patch is rough but maybe it fixes the issue. Thanks.

**Comment by bqphone** [comment]
I didn't get any update notification for telegram yet. Till then the problem still exists.

**Comment by Flohack74** [comment]
I will test it for him @dfiloni ;)

**Comment by bqphone** [comment]
sorry i missed dfiloni solution, will test it asap

**Comment by Flohack74** [comment]
We will release this fix in 2.4.41 soon!

**Comment by Flohack74** [comment]
Sorry latest Q/A shows its not solved right now...

**Comment by bqphone** [comment]
sadly the bug is not fixed yet with the new update.

**Comment by Flohack74** [comment]
Hello,

I debugged now server/client communication, and it seems it´s some kind of bug on the server. While the user id is already reported as invalid, the server still sends user, dialog and message data for this stale dialog. The app does indeed delete the chat (it disappears for a moment), but then with the next update its back.

Will need to investigate how to still get rid of it ;)

**Comment by bqphone** [comment]
Where can i get the beta version?

**Comment by Flohack74** [comment]
https://github.com/ubports/telegram-app/releases/download/v2.5.0/com.ubuntu.telegram_2.5.0.0_armhf.click

**Comment by bqphone** [comment]
It is fixed, great job mate.

**Comment by Flohack74** [comment]
You are welcome. But probably it was due to the API upgrade to 41, not because I fixed it hehe :)
