### ISSUE TITLE
"writing a message"

### ISSUE THREAD

**Issue by alexanderisme** [ubports/telegram-app#44]
When you write a message normally you only need to write, not more. But since there is the smiley icon (for stickers), the attachment icon and the record icon, there is only a really little box to write. 
Is it needed to have all this icons even when you write? Would it be possible to hide them when writing in order to have a bigger text box?

![image](https://user-images.githubusercontent.com/29466789/27201074-92c59ba0-521c-11e7-8ee7-f33e864c1b25.png)

**Comment by Flohack74** [comment]
Hmm good idea, but how to get the buttons back if I change my mind? Then I would need to click outside, effectively dismissing the keyboard, and then click on one of the buttons.

**Comment by alexanderisme** [comment]
Yes it's true! I had not thought about the changing mind idea ;) But it's true, it happens to me as well ! 
Your solution seems to be nice: while writing the icons are hidden, by hiding the keyboard the icons reappear !
 I hope only it will not make it buggy because it has to reload the text and reorganise the lines if the text box become smaller

**Comment by Flohack74** [comment]
@dfiloni What you think, can we improve this with a little patch? =)

**Comment by Gabriele69** [comment]
![before_tap](https://user-images.githubusercontent.com/17642335/27385903-61b09610-5694-11e7-90ca-13b11e561cc7.png)

![after_tap](https://user-images.githubusercontent.com/17642335/27385910-67a2b602-5694-11e7-8fdd-72326c9dd7fe.png)

This is my personal suggestion

**Comment by mymike00** [comment]
And to send the message how would you do? Personally I like the Flohack suggest: while writing send button and when you dismiss the keyboard the other

**Comment by Gabriele69** [comment]
Now, when you starts to write a messages, the microphone icon turns into the blue arrow for sending. In my proposal, just beginning to write the message, next to the three bars, the blue arrow might appear. Or, the three bars become a different icon that works in the following way: short press (tap) message sending, long press opening of the menu (emoticon and attachments).
G

**Comment by alexanderisme** [comment]
@Gabriele69 , I really like your suggestion !!!

I will only try to explain the idea of @Flohack74 and @mymike00 with images  (if I have well understood!) : 


That's the idea: when you type a message the only possibility is to send, so the writing box can take the maximum place:
Image A)
![telegram 1](https://user-images.githubusercontent.com/29466789/27508534-9f64675c-58e7-11e7-890a-a1e97d9934ba.png)

But if you want to do something else, you can simply hide the keyboard and here you have new choices:
Image B)
![telegram 2](https://user-images.githubusercontent.com/29466789/27508537-a6aff562-58e7-11e7-9ea0-443b8eefc1ed.png)


Or maybe more like that (=have a smaller box and all choices possible!):
Image C)
![telegram 3](https://user-images.githubusercontent.com/29466789/27508536-a68c9554-58e7-11e7-9c65-e865326653f3.png)

I don't know which one is the best solution, I really like all the ideas! The only point in @Gabriele69 solution is that there is no sending option, but it can be solved like that:
Image D)
![telegram 4](https://user-images.githubusercontent.com/29466789/27508659-390bf56c-58ea-11e7-8652-25c2304e46a8.png)

But then there is more place for the text box that is lost..

**Comment by dfiloni** [comment]
This was already fixed in commit 7ef5958 , Image A and Image B describe the new behavior. Thank you for all the proposals.

**Comment by Flohack74** [comment]
We will make a release for that soon. Closing here ;)
