### ISSUE TITLE
Keyboard kept open upon opening stickers with v2.4.41.0

### ISSUE THREAD

**Issue by zubozrout** [ubports/telegram-app#54]
Hello,
since v2.4.41.0 the on-screen keyboard stays open if you click on stickers. This could work on large screens but on small phones like MX4 the box with all the stickers doesn't fit to display and is cut off on the top - which makes using stickers a bit unusable unless you manually hide the keyboard .

With previous releases this worked just fine but once "hiding some buttons on text field not empty" was implemented this stopped working.

The expected behavior is to either have the keyboard shown or the stickers shown but to avoid having both on screen at one time.

Thank you very much for looking into this.

Martin

**Comment by Flohack74** [comment]
Hi, yes we are aware already, and working on a fix =)

**Comment by dfiloni** [comment]
Already fixed in commit b2bb747 , other issues ware found in attachments component too and they were fixed in the same commit. Thank you for reporting ;)

**Comment by Flohack74** [comment]
Fixed in https://github.com/ubports/telegram-app/releases/tag/v2.4.41.1
