### ISSUE TITLE
Failure to hide the buttons

### ISSUE THREAD

**Issue by Gabriele69** [ubports/telegram-app#55]
Hello.
I installed the new version (V2 4.41) on my BQ Aquaris 4.5 (OTA1) but the buttons (stikers and attachments) remain visible.
The only thing that happens when you start typing the message is the disappearance of the "audio" button and the appearance of the blue arrow for sending.
This fact, in addition to not changing the box size to write the message, makes it impossible to attach a voice message after typing text, because the audio attachment button can not be retrieved again.

Thanks again for your wonderful contribution !

GM

**Comment by Flohack74** [comment]
Can you test again we made a hotfix...

**Comment by Gabriele69** [comment]
Perfect. Now it's OK !
Thank You !!

G

**Comment by Flohack74** [comment]
Welcome ;)
