### ISSUE TITLE
Change notification icons faster

### ISSUE THREAD

**Issue by Flohack74** [ubports/telegram-app#60]
_From @ChloeWolfieGirl on July 3, 2017 19:40_

If someone changes there Profile picture on telegram, often the notifications will continue to use an old profile picture.
I don't know if this affects other apps.

_Copied from original issue: ubports/ubports-touch#145_

**Comment by Flohack74** [comment]
_From @NeoTheThird on July 9, 2017 20:40_

Please report this on github.com/ubports/telegram-app

**Comment by dfiloni** [comment]
Fixed in commit 1f712ad

**Comment by Flohack74** [comment]
How can I test this? =)

**Comment by dfiloni** [comment]
Aren't notifications working for you?

Have you tried time ago to logout telegram, delete your Ubuntu account from mobile phone, deassociate it from web interface and create a new Ubuntu account? This worked for me months ago when notifications stopped working.

**Comment by Flohack74** [comment]
They do but how can I verify the picture change? Ask a friend to change it?

**Comment by dfiloni** [comment]
Yep, I think it's the only way.

Please note: during notifications we don't download the avatar so you'll see the new avatar only once it is downloaded by the app (so you have to open telegram app before you see the notification with the new avatar)
