### ISSUE TITLE
When uploading a file, the part saying how much of the file is sent it's not easily readable

### ISSUE THREAD

**Issue by TronFourtyTwo** [ubports/telegram-app#65]
I attach a screenshot since I suppose it's not explained well for my not good english, sorry.
![screenshot20170802_145239498](https://user-images.githubusercontent.com/18293963/28874777-8f90844e-7793-11e7-8795-64ff16497186.png)
I hardly read 20MB/154MB.

**Comment by Flohack74** [comment]
@dfiloni can we increase the progressbar a bit;) and set nice/better colors? Where is this defined no idea ;)

**Comment by Flohack74** [comment]
So here is my proposal:

![grafik](https://user-images.githubusercontent.com/16186470/29007097-8da75c9a-7afc-11e7-8100-3b9ef1f08744.png)

From left to right: Uploading, Uploaded, Downloading, Downloaded. What you thin (color can be changed ofc :))

**Comment by TronFourtyTwo** [comment]
Great! Now is much more readable

**Comment by Flohack74** [comment]
So this is now final solution, I made now the shadows like on the time display, and changed color again to white. Everything else did not work:

![grafik](https://user-images.githubusercontent.com/16186470/29223016-4d1a1e70-7ec5-11e7-9371-540a09c879c4.png)
