### ISSUE TITLE
Show status indicators instead of text for "not online" and "connecting to servers"

### ISSUE THREAD

**Issue by Flohack74** [ubports/telegram-app#68]
Currently the title text in the pages is being swapped to "Waiting for network" and "Connecting" when these conditions are met. I think about the following idea:
![telegram-new-status](https://user-images.githubusercontent.com/16186470/28995662-4069efbe-79ef-11e7-8c29-5a38db19d200.gif)

That way the title of the chat stays readable, we got a nice animation and can indicate various states there also.

**Comment by TronFourtyTwo** [comment]
I think it is a very good idea and design.

**Comment by ChloeWolfieGirl** [comment]
I agree with TronFourtyTwo
