### ISSUE TITLE
Chat animations

### ISSUE THREAD

**Issue by Jujuyeh** [ubports/telegram-app#8]
The audio message button sometimes doesn't work or it's animation when it's recording takes some time to show up. Also, there's no animation when you receive a message or you send it on chat.

I recommend adding a counter that shows how long the user is talking while recording the audio message.

**Comment by dfiloni** [comment]
> The audio message button sometimes doesn't work or it's animation when it's recording takes some time to show up.

This is not a telegram-app issue, we simply call QAudioRecorded. messaging-app is affected too.

> I recommend adding a counter that shows how long the user is talking while recording the audio message.

Done! Commit: 2831dad49f06db994549c7977c9b0a5c40e0f647

> Also, there's no animation when you receive a message or you send it on chat.

I disabled animations in commit aa7ff9051c00a8bb53f749d5aad5793ff6ffdc40 , they were causing messages overlapping: the media preview in a message takes time to load and it changes the message height, at the same time animations were changing all messages position.

**Comment by Flohack74** [comment]
I close this for the moment. Disabling animations has done a good job for the message window, and as Devid said the audio message button is not under our control =) - the recording time counter has been done.
