### ISSUE TITLE
Remove notifications on messages which were already seen from the system tray

### ISSUE THREAD

**Issue by zubozrout** [ubports/telegram-app#92]
Hello,
is there a way to remove notifications (not only for Telegram I suppose) if the message was already seen on other device?

I am sometimes also getting notifications with delay even for messages I've seen even on my Ubuntu Phone so there should definitely be some kind of a check right at the start (before popping the notification up on a phone).

And once a notification is up it should be followed by further checks to remove it in case the message it represents was already seen on any device.

Thank you very much.

**Comment by Flohack74** [comment]
Sorry this is not possible by the nature the push service is done right now, Telegram servers do not send follow-up messages when a message has been read.

**Comment by Flohack74** [comment]
Ok I was wrong, it is possible. Will be live in 2.5.3 finally :)
