### ISSUE TITLE
Display gif animations in chat threads

### ISSUE THREAD

**Issue by zubozrout** [ubports/telegram-app#93]
Hello,
Telegram Web, Desktop and Android app display gif animations while the Ubuntu app only shows an empty card. Official app also allows to send saved gif animations the same way as stickers but I suppose that is harder to implement than just displaying those gif images in threads.

Is making this work just a matter of utilizing this http://doc.qt.io/qt-5/qml-qtquick-animatedimage.html or is there more to it?

Thank you very much for looking into this.

**Comment by Flohack74** [comment]
Hello, there is already a ticket for this here: https://github.com/ubports/telegram-app/issues/29 - currently nobody looked into a solution but probably its not that hard.

BR
